package common;

public enum RequestType {
    ADD_GAME,
    REMOVE_GAME,
    UPDATE_GAME_RISK,
    UPDATE_GAME_BET_LIMITS,
    GET_PROVIDER_STATS,
    GET_PLAYER_STATS,
    START_PROVIDER_REDUCE,
    START_PLAYER_REDUCE,
    MAP_PROVIDER_STATS,
    MAP_PLAYER_STATS,
    GET_REDUCED_RESULT,
    GET_ALL_GAMES,
    SEARCH_GAMES,
    PLACE_BET,
    GET_RANDOM_NUMBER,
    ADD_BALANCE,
    RATE_GAME
}
